#Data Acquisition and ETL Case Study

1.Objective

As a Data Analyst, you have received data from different departments in different file
formats. Your task is to extract the data, clean it, integrate it, store it in a database, and
perform analysis.

######You are provided with the following files:
1. population.csv
2. gdp.xlsx
3. internet_users.json
4. literacy_rate.xml

#Task 1

Read the Population dataset from the CSV file.
Hint:
1. Use the pandas library.
2. Display the first five rows.
3. Check the shape and data types.

In [59]:
import pandas as pd

In [60]:
#1
population = pd.read_csv('/content/population.csv')

In [61]:
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [62]:
#2
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [63]:
#3
population.shape

(25, 2)

In [64]:
#3
population.dtypes

country       object
population     int64
dtype: object

#Task 2

Read the GDP dataset from the Excel file.
Hint:
1. Use the appropriate pandas function.
2. Display column names and data types.

In [65]:
df_gdp =pd.read_excel("/content/gdp.xlsx")

In [66]:
df_gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [67]:
df_gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [68]:

df_gdp.dtypes

Country    object
GDP         int64
dtype: object

#Task 3

Read the Internet Users dataset from the JSON file.
Hint:
1. Use either the json module or pandas.
2. Convert the data into a DataFrame.

In [69]:
net_users =pd.read_json("/content/internet_users.json")

In [70]:
net_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#Task 4

Read the Literacy Rate dataset from the XML file.
Hint:
1. Use xml.etree.ElementTree or pandas.read_xml().
2. Extract all required fields into a DataFrame.

In [71]:
df_lit = pd.read_xml("/content/literacy_rate.xml")

In [72]:
df_lit

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Task 5

Explore each dataset.
Find the following:
1. Number of rows
2. Number of columns
3. Column names
4. Data types
5. Missing values
6. Duplicate records

In [73]:
# population

len(population) # Number of rows

25

In [74]:
len(population.columns) # number of columns

2

In [75]:
population.columns # column names

Index(['country', 'population'], dtype='object')

In [76]:
population.dtypes # data types

country       object
population     int64
dtype: object

In [77]:
population.isnull().sum() # missing values

country       0
population    0
dtype: int64

In [78]:
population.duplicated().sum()

np.int64(0)

In [79]:
# gdp xlsv

len(df_gdp) # Number of rows

25

In [80]:
len(df_gdp.columns) # number of columns

2

In [81]:
df_gdp.columns # column names

Index(['Country', 'GDP'], dtype='object')

In [82]:
df_gdp.dtypes # data types

Country    object
GDP         int64
dtype: object

In [83]:
df_gdp.isnull().sum() # missing values

Country    0
GDP        0
dtype: int64

In [84]:
df_gdp.duplicated().sum()  # duplicate values

np.int64(0)

In [85]:
# internet users

len(net_users) # Number of rows

25

In [86]:
len(net_users.columns) # number of columns

2

In [87]:
net_users.columns

Index(['country', 'internet_users'], dtype='object')

In [88]:
net_users.dtypes # data types

country           object
internet_users     int64
dtype: object

In [89]:
net_users.isnull().sum() # missing values

country           0
internet_users    0
dtype: int64

In [90]:

net_users.duplicated().sum()  # duplicate values

np.int64(0)

In [91]:
# literacy_users

len(df_lit) # Number of rows

25

In [92]:
len(df_lit.columns) # number of columns

2

In [93]:

df_lit.columns

Index(['name', 'literacy_rate'], dtype='object')

In [94]:
df_lit.dtypes # data types

name              object
literacy_rate    float64
dtype: object

In [95]:
df_lit.isnull().sum() # missing values

name             0
literacy_rate    0
dtype: int64

In [96]:
df_lit.duplicated().sum()  # duplicate values

np.int64(0)

#Task 6

Rename columns wherever necessary so that all datasets have a common column
name for merging.
Hint:
1. Example: Country → country

In [97]:
df_gdp = df_gdp.rename(columns={'Country': 'country'})

In [98]:
df_gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [99]:
df_lit = df_lit.rename(columns={'name': 'country'})

In [100]:
df_lit

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Task 7

Convert the required columns into appropriate numeric data types.

#Task 8

Merge all four datasets into one DataFrame.
Hint:
1. Use the common column (country)
2. Choose an appropriate join method.

In [101]:
merged = population.merge(df_gdp, on = 'country', how ='inner')\
.merge(net_users, on='country',how ='inner' )\
.merge(df_lit, on='country',how ='inner' )

In [102]:
merged

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

#Task 9

Create the following calculated columns:
1. Internet Penetration (%)
2. GDP Per Capita

. Hint:
*Round the calculated values to two decimal places.

In [103]:
merged["internet_penetration (%)"] = (
    merged["internet_users"] / merged["population"] * 100
).round(2)

In [104]:
merged["GDP_Per_Capita"] = (
    merged["GDP"] * 1000000 / merged["population"]
).round(2)

In [105]:
merged

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP_Per_Capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,56550.68
6,France,65273511,3211000,62000000,99.0,94.98,49193.00
7,Italy,60461826,2420000,56000000,99.0,92.62,40025.25
8,Canada,38005238,2250000,36000000,99.0,94.72,59202.37
9,Australia,25687041,1880000,24000000,99.0,93.43,73188.66
10,Brazil,212559417,2330000,181000000,93.2,85.15,10961.64
11,Russia,145934462,2200000,125000000,99.7,85.65,15075.26
12,South Korea,51780579,1800000,50000000,98.8,96.56,34762.07
13,Spain,46754778,1710000,44000000,98.6,94.11,36573.80
14,Mexico,128932753,1810000,102000000,95.4,79.11,14038.33
15,Indonesia,273523615,1500000,212000000,96.0,77.51,5483.99
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,31596.60
17,Turkey,84339067,1350000,69000000,96.7,81.81,16006.82
18,South Africa,59308690,410000,43000000,95.0,72.50,6912.98
19,Argentina,45195774,640000,41000000,99.1,90.72,14160.62
20,Netherlands,17441139,1150000,17000000,99.0,97.47,65936.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,108612.48
22,Sweden,10353442,650000,10100000,99.0,97.55,62781.05
23,Norway,5421241,580000,5300000,100.0,97.76,106986.57
24,Singapore,5850342,530000,5600000,97.5,95.72,90592.99

#Task 10

Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’ .
1. Hint:
● Use the sqlite3 library.
● Load the DataFrame using pandas.

In [106]:
import sqlite3

In [107]:
conn =sqlite3.connect("country_statistics.db")
merged.to_sql("country_statistics",conn,
              if_exists = "replace",
              index = False
              )
conn.close()

In [108]:
conn = sqlite3.connect("country_statistics.db")

df = pd.read_sql("SELECT * FROM country_statistics", conn)

conn.close()

df

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP_Per_Capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,56550.68
6,France,65273511,3211000,62000000,99.0,94.98,49193.00
7,Italy,60461826,2420000,56000000,99.0,92.62,40025.25
8,Canada,38005238,2250000,36000000,99.0,94.72,59202.37
9,Australia,25687041,1880000,24000000,99.0,93.43,73188.66
10,Brazil,212559417,2330000,181000000,93.2,85.15,10961.64
11,Russia,145934462,2200000,125000000,99.7,85.65,15075.26
12,South Korea,51780579,1800000,50000000,98.8,96.56,34762.07
13,Spain,46754778,1710000,44000000,98.6,94.11,36573.80
14,Mexico,128932753,1810000,102000000,95.4,79.11,14038.33
15,Indonesia,273523615,1500000,212000000,96.0,77.51,5483.99
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,31596.60
17,Turkey,84339067,1350000,69000000,96.7,81.81,16006.82
18,South Africa,59308690,410000,43000000,95.0,72.50,6912.98
19,Argentina,45195774,640000,41000000,99.1,90.72,14160.62
20,Netherlands,17441139,1150000,17000000,99.0,97.47,65936.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,108612.48
22,Sweden,10353442,650000,10100000,99.0,97.55,62781.05
23,Norway,5421241,580000,5300000,100.0,97.76,106986.57
24,Singapore,5850342,530000,5600000,97.5,95.72,90592.99

#Task 11

Verify that the data has been loaded successfully.

Hint:
Retrieve the first five records from the SQLite table.

In [109]:
df.head()

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP_Per_Capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47

# Data Analysis Using Pandas

In [110]:
#List the Top 5 countries by GDP.

merged.nlargest(5,"GDP")[['country','GDP']]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [111]:


#List the Top 5 countries by population.

merged.nlargest(5,"population")[['country','population']]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [112]:
# Calculate the average literacy rate.

merged['literacy_rate'].mean()

np.float64(97.248)

In [113]:
# List all countries having a literacy rate greater than 90%.

merged[merged['literacy_rate']>90][['country','literacy_rate' ]]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [114]:
# List all countries having an internet penetration greater than 70%.

merged[merged['internet_penetration (%)']>90][['country','internet_penetration (%)' ]]

           country  internet_penetration (%)
0    United States                     94.26
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
12     South Korea                     96.56
13           Spain                     94.11
16    Saudi Arabia                     97.66
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

In [115]:
# List the Top 5 countries by GDP per capita.

merged.nlargest(5, "GDP_Per_Capita")[["country","GDP_Per_Capita"]]

          country  GDP_Per_Capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66

In [116]:
#calculate the total population represented in the dataset.
merged['population'].sum()

np.int64(4720039725)

In [117]:
#8 Calculate the average internet penetration across all countries.

merged['internet_penetration (%)'].mean()

np.float64(89.6596)

In [118]:
# Identify the country having the highest number of internet users.
merged.loc[merged["internet_users"].idxmax(),['country','internet_users']]

country                China
internet_users    1080000000
Name: 1, dtype: object

In [119]:
#Find the correlation between Literacy Rate and Internet Penetration.
merged['literacy_rate'].corr(merged['internet_penetration (%)'])

np.float64(0.77279756813985)

#Data Analysis Using SQL

In [120]:
# Display the Top 5 countries by GDP. using sqlite
conn=sqlite3.connect('country_statistics.db')

pd.read_sql("""
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
""", conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [121]:
#  Find the average literacy rate.

pd.read_sql("""
SELECT AVG(literacy_rate) AS
average_litracy_rate
from country_statistics
""", conn)

   average_litracy_rate
0                97.248

In [122]:
# Display all countries having literacy rate above 90%.

pd.read_sql(
    """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
ORDER BY literacy_rate DESC
""",
    conn,
)

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3    United States           99.0
4            Japan           99.0
5          Germany           99.0
6   United Kingdom           99.0
7           France           99.0
8            Italy           99.0
9           Canada           99.0
10       Australia           99.0
11     Netherlands           99.0
12     Switzerland           99.0
13          Sweden           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

In [123]:
# Find the Top 5 countries with the highest internet penetration.

pd.read_sql(
    """
SELECT country, `internet_penetration (%)`
FROM country_statistics
ORDER BY `internet_penetration (%)` DESC
LIMIT 5
""",
    conn,
)

        country  internet_penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [124]:
#Calculate the total population.

pd.read_sql(
    """
SELECT SUM(population) AS total_population
FROM country_statistics
""",
    conn,
)

   total_population
0        4720039725

In [125]:
# Find the country with the highest GDP per capita.
pd.read_sql(
    """
SELECT country, GDP_Per_Capita
FROM country_statistics
ORDER BY GDP_Per_Capita DESC
LIMIT 1
""",
    conn,
)

       country  GDP_Per_Capita
0  Switzerland       108612.48

In [126]:
#Export the final merged dataset as a CSV file
df = pd.read_sql("SELECT * FROM country_statistics", conn)

df.to_csv("final_merged_dataset.csv", index=False)

print("CSV file exported successfully!")

CSV file exported successfully!

In [127]:
# Sort the dataset in descending order of GDP per Capita and display the Top 10 countries.
pd.read_sql( """
SELECT country,  GDP_Per_Capita
FROM country_statistics
ORDER BY  GDP_Per_Capita DESC
LIMIT 10
""", conn)

          country  GDP_Per_Capita
0     Switzerland       108612.48
1          Norway       106986.57
2   United States        92144.28
3       Singapore        90592.99
4       Australia        73188.66
5     Netherlands        65936.06
6          Sweden        62781.05
7          Canada        59202.37
8         Germany        56991.47
9  United Kingdom        56550.68